### PR TITLE
Issue with Salesforce org list command resolved

### PR DESCRIPTION
**Pull request by ashuk30**
Issue with Salesforce org list command resolved

### CODE REVIEW

**Comment by hknokh2** [comment]
Hello
Thanks for the contribution.
Which problem you've solved with your fix ?
Please complete CLA signature to allow me to merge.

**Comment by ashuk30** [comment]
Hi team,

I have already signed a cla. And basically we are facing an issue while
trying to load the orgs in the tool. Then I found out, the code was killing
the main process before the whole child process was returning the data.

It comes when we have multiple stdout data coming in cases where there are
warnings in the response header from sfdx command response.

**Comment by jimbasilio** [comment]
Any chance this gets merged?

**Comment by jimbasilio** [comment]
> Hello Thanks for the contribution. Which problem you've solved with your fix ? Please complete CLA signature to allow me to merge.

I ran the PR code and it was able to pull my orgs via sfdx. Without the PR, I could not load the orgs.

**Comment by hknokh2** [comment]
Sorry, but that still appears as the cla is not signed yet.
Sometimes it can be an issue with signing to cla. Try to resign please.
I hope you can use your fixed local version for your orgs untill the PR will get merged.

**Comment by hknokh2** [comment]
If you've already signed, may be you can close this PR, and create a new PR from the latest master and submit this change again.

**Comment by hknokh** [comment]
Created and merged a new PR which contains your changes from my side
https://github.com/forcedotcom/SFDX-Data-Move-Utility-Desktop-App/pull/36
Yours is closed.
Thanks again for your work on SFDMU.

**Pull request closed without merging**
