### PR TITLE
Break up EntityDefinition queries to allow compatibility with bigger orgs. 

### PR DESCRIPTION
**Pull request by zerkz**
The max limit for any entity definition query is 2000, Salesforce limit.

This change the query in two different ways (inverses of each other) to get the full list (up to 4000 records atleast..), combines them, and sorts before returning the records.

This fixes an issue brought up before (#220) but it seems that the issue repository has moved or has been deleted?

### CODE REVIEW

**Comment by zerkz** [comment]
@hknokh Hi, did something happen to the "Issues" tab for both the desktop app repo and the data utility repo? Are bug reports still accepted?

**Comment by hknokh** [comment]
Hello @zerkz 
Sounds good.
1. But why you did't include ContentVersion with or operator like before? It will not be included in your queries because it's not IsEverDeletable and will not pass the final filter.
2. Why you need developername in the query ?
----
Regarding the support, I stopped temporarily accepting tickets due lack of time. 
I plan to reopen the support soon, for now it's not available.

**Comment by zerkz** [comment]
@hknokh 

For number 1, this was a mistake. good catch. I likely left it out on accident when rebasing my branch. 
For number 2, this might of been used for debugging purposes. I will remove it.

Thanks! 


--- regarding Issues/support, totally get that. This is a big project you are maintaining by yourself. Having the issues open may still be helpful (others like myself may be able to enlist bug reports and provide on our own fixes). But I could see the issues list getting pretty swamped with low quality stuff too. Hope you find something that works for you.

**Comment by hknokh** [comment]
Thank you @zerkz 
I merged your request.
Regarding the support you are definitely right, it's very helpful and I am really thinking about how to re-organize this to make it more effective and less painful for me).

**Pull request merged**
